# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/computer_composition/cpu_54/cpu_54.cache/wt [current_project]
set_property parent.project_path D:/computer_composition/cpu_54/cpu_54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/computer_composition/cpu_54/materials/cpu54_frontsim/mips_54_mars_simulate_student_ForWeb_2024.coe
add_files -quiet d:/computer_composition/cpu_54/cpu_54.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files d:/computer_composition/cpu_54/cpu_54.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  D:/computer_composition/cpu_54/cpu_54.srcs/sources_1/new/regfile.v
  D:/computer_composition/cpu_54/cpu_54.srcs/sources_1/new/scinstmem.v
  D:/computer_composition/cpu_54/cpu_54.srcs/sources_1/new/sccpu.v
  D:/computer_composition/cpu_54/cpu_54.srcs/sources_1/new/scdatamem.v
  D:/computer_composition/cpu_54/cpu_54.srcs/sources_1/new/postsim_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/computer_composition/cpu_54/cpu_54.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/computer_composition/cpu_54/cpu_54.srcs/constrs_1/new/icf.xdc]


synth_design -top postsim_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef postsim_top.dcp

catch { report_utilization -file postsim_top_utilization_synth.rpt -pb postsim_top_utilization_synth.pb }
