######################################################################
#
# File name : postsim_tb_compile.do
# Created on: Tue Sep 01 11:15:14 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"postsim_tb_time_synth.v" \
"../../../../cpu_54.srcs/sim_1/new/postsim_tb.v" \


quit -force

