######################################################################
#
# File name : postsim_tb_wave.do
# Created on: Tue Sep 01 11:15:23 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
