######################################################################
#
# File name : postsim_tb.udo
# Created on: Sun Jun 21 20:19:08 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
