######################################################################
#
# File name : postsim_tb_simulate.do
# Created on: Tue Sep 01 11:15:23 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.postsim_tb xil_defaultlib.glbl

do {postsim_tb_wave.do}

view wave
view structure
view signals

do {postsim_tb.udo}

run -all
