######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Tue Sep 01 10:28:44 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
