######################################################################
#
# File name : _246tb_ex10_tb_compile.do
# Created on: Tue Sep 01 10:28:32 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/dist_mem_gen_v8_0_10
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../cpu_54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../cpu_54.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../cpu_54.srcs/sources_1/new/regfile.v" \
"../../../cpu_54.srcs/sources_1/new/scinstmem.v" \
"../../../cpu_54.srcs/sources_1/new/sccpu.v" \
"../../../cpu_54.srcs/sources_1/new/scdatamem.v" \
"../../../cpu_54.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../cpu_54.srcs/sim_1/new/testbench_cpu54_single.v" \

# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

